//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySoftWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PeopleData
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string Gmail { get; set; }
        public string Region { get; set; }
        public string SourceId { get; set; }
    }
}
